services:
  sgu-pdi-service:
    image: sgu-pdi-service
    build: .
    ports:
      - "8084:8084"
    container_name: sgu-pdi-service
    command: mvn spring-boot:run
    networks:
      - sgu-networks
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://sgu-pdi-db:5432/pdi
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      sgu-pdi-db:
        condition: service_healthy
    volumes:
      - ./storage:/app/storage

  sgu-pdi-db:
    image: postgres:16.0
    restart: always
    environment:
      POSTGRES_DB: pdi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      TZ: America/Sao_Paulo
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d prae"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "5437:5432"
    networks:
      - sgu-networks
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pg-data:
    driver: local

networks:
  sgu-networks:
    external: true