spring:
  application:
    name: sgu-pdi-service
  profiles:
    active: docker

  config:
    import: "configserver:"

  cloud:
    config:
      uri: http://config-service:8888
      fail-fast: true
